apiVersion: apps/v1
kind: Deployment

# Deployment 기본 정보
metadata:
    name: mysql-deployment # Deployment 이름

# Deployment 세부 정보
spec:
    replicas: 1 # 생성할 파드의 복제본 개수
    selector:
        matchLabels:
            app: mysql-db # 아래에서 정의한 Pod 중 'app: mysql-db'이라는 값을 가진 파드를 선택

    # 배포할 Pod 정의
    template:
        metadata:
            labels: # 레이블 (= 카테고리)
                app: mysql-db
        spec:
            containers:
                - name: mysql-container # 컨테이너 이름
                  image: mysql:8.0 # 컨테이너를 생성할 때 사용할 이미지 (버전 명시)
                  ports:
                      - containerPort: 3306 # 컨테이너에서 사용하는 포트를 명시적으로 표현
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: mysql-root-password
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: mysql-config
                                key: mysql-database
                  volumeMounts:
                      - name: mysql-persistent-storage
                        mountPath: /var/lib/mysql
            volumes: # 이 부분이 template.spec 아래로 이동!
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                      claimName: mysql-pvc
