apiVersion: v1
kind: Service

metadata:
    name: spring-service

spec:
    type: NodePort
    selector:
        app: backend-app
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
          nodePort: 30000
